"""
Synthetic data generator for the solution showcase projects.

Company: Tidewell Distribution LLC, an invented UAE distributor of food,
household and personal care products. Every name, number and record below is
generated by this script. Nothing comes from a real business.

Period: 1 Oct 2024 to 30 Sep 2026 (24 months). Snapshot date: 30 Sep 2026.
Fixed random seed, so every run produces identical files.

Usage:  python generate_data.py [output_folder]
Needs:  Python 3.10+, numpy, pandas
"""
import sys, os, json
import numpy as np
import pandas as pd

SEED = 20261001
START = pd.Timestamp("2024-10-01")
END = pd.Timestamp("2026-09-30")          # snapshot date
rng = np.random.default_rng(SEED)
OUT = sys.argv[1] if len(sys.argv) > 1 else "data"
os.makedirs(OUT, exist_ok=True)

BRANCHES = ["Jebel Ali DC", "Al Quoz Depot", "Sharjah Depot"]
BRANCH_W = np.array([0.45, 0.32, 0.23])
EMIRATES = {"Jebel Ali DC": ["Dubai", "Abu Dhabi"], "Al Quoz Depot": ["Dubai"],
            "Sharjah Depot": ["Sharjah", "Ajman", "Ras Al Khaimah", "Umm Al Quwain", "Fujairah"]}

# ---------------------------------------------------------------- products
CATS = {
    "Beverages":        (["Juice", "Iced Tea", "Sparkling Water", "Still Water", "Laban Drink", "Energy Drink"], (2.5, 9)),
    "Dry Grocery":      (["Basmati Rice", "Lentils", "Pasta", "Flour", "Sugar", "Chickpeas", "Oats"], (4, 45)),
    "Snacks":           (["Potato Chips", "Date Bars", "Mixed Nuts", "Crackers", "Wafers"], (1.5, 18)),
    "Dairy and Chilled":(["Yoghurt", "Labneh", "Cheese Slices", "Butter", "Fresh Cream"], (3, 28)),
    "Household":        (["Dish Liquid", "Floor Cleaner", "Laundry Powder", "Bin Bags", "Kitchen Towel", "Glass Cleaner"], (5, 55)),
    "Personal Care":    (["Hand Wash", "Shampoo", "Body Lotion", "Toothpaste", "Wet Wipes"], (6, 40)),
    "Paper and Disposables": (["Paper Cups", "Foil Roll", "Cling Film", "Napkins", "Takeaway Boxes"], (8, 120)),
    "Frozen":           (["Frozen Peas", "Chicken Nuggets", "Paratha", "Mixed Vegetables", "Fish Fingers"], (7, 48)),
}
BRANDS = ["Sandleaf", "Brightmoor", "Oasiva", "Corniche Gold", "Falconridge", "Mirava", "Duneberry", "Qamra", "Pearlbay", "Tidewell Select"]
VARIANTS = ["Classic", "Lite", "Family Pack", "Value", "Premium", "Mini", "Bulk"]
SIZES = ["250g", "500g", "1kg", "2kg", "5kg", "330ml", "500ml", "1L", "1.5L", "Pack of 6", "Pack of 12", "Pack of 24"]

rows = []; sku_n = 1000
for cat, (items, (lo, hi)) in CATS.items():
    for item in items:
        for _ in range(rng.integers(5, 9)):
            sku_n += 1
            price = round(float(rng.uniform(lo, hi)), 2)
            margin = float(rng.uniform(0.12, 0.34))
            rows.append(dict(sku=f"SKU{sku_n}", product_name=f"{rng.choice(BRANDS)} {item} {rng.choice(VARIANTS)} {rng.choice(SIZES)}",
                             brand=None, category=cat, unit_price=price, unit_cost=round(price * (1 - margin), 2),
                             lead_time_days=int(rng.choice([5, 7, 10, 14, 21, 30]))))
products = pd.DataFrame(rows)
products["brand"] = products["product_name"].str.split(" ").str[0]
products.loc[products["product_name"].str.startswith(("Corniche", "Tidewell")), "brand"] = products["product_name"].str.split(" ").str[:2].str.join(" ")
P = len(products)
pop = rng.pareto(1.3, P) + 0.05                      # long tail popularity
slow = rng.random(P) < 0.12                           # deliberately slow movers
pop[slow] *= 0.04
products["popularity"] = pop / pop.sum()

# ---------------------------------------------------------------- customers
PRE = ["Blue Harbour", "Green Palm", "Silver Dune", "Golden Creek", "Sunrise", "Al Waha", "Seaside", "Crescent", "Oasis Corner", "Red Sand",
       "Royal Date", "Nakheel View", "Marina Bay", "Desert Rose", "Lulu Tree", "Coral Point", "Falcon Gate", "Old Souk", "Garden City", "Mangrove",
       "Starlight", "Twin Towers", "Rashidiya", "Barsha Heights", "Karama Lane", "Bluewater", "Jasmine", "Saffron Street", "Pearl Coast", "Al Fahad"]
TYPES = {"Supermarket": ("Supermarket", 0.25), "Grocery": ("Grocery", 0.30), "Restaurant": ("Restaurant", 0.17),
         "Cafe": ("Cafe", 0.10), "Pharmacy": ("Pharmacy", 0.08), "Hotel": ("Hotel Supplies", 0.05), "Catering": ("Catering", 0.05)}
AREAS = ["Deira", "Karama", "Al Nahda", "Muwaileh", "Al Barsha", "Mirdif", "Al Khan", "Musaffah", "Al Qusais", "Al Majaz", "Rolla", "Al Warqa"]
SALESPEOPLE = ["Aisha K.", "Rahul M.", "Fatima S.", "Omar H.", "Priya N.", "Imran Q.", "Leena D.", "Yousef A.", "Neha R.", "Karim B."]
names = set(); cust = []
for i in range(450):
    ch = rng.choice(list(TYPES), p=[v[1] for v in TYPES.values()])
    while True:
        nm = f"{rng.choice(PRE)} {TYPES[ch][0]}" + ("" if rng.random() < .6 else f" {rng.choice(['LLC', 'Trading', 'Co.', 'FZE'])}")
        if nm in names: nm += f" ({rng.choice(AREAS)})"
        if nm not in names: break
    names.add(nm)
    br = rng.choice(BRANCHES, p=BRANCH_W)
    size = float(rng.pareto(1.1) + 0.2)
    cust.append(dict(customer_id=f"C{2001 + i}", customer_name=nm, channel=ch, branch=br, emirate=str(rng.choice(EMIRATES[br])),
                     credit_terms_days=int(rng.choice([30, 30, 45, 60, 60, 90])), salesperson=str(rng.choice(SALESPEOPLE)), size=size,
                     pay_delay_mean=float(rng.choice([-3, 2, 6, 12, 25, 45], p=[.15, .3, .25, .15, .1, .05]))))
customers = pd.DataFrame(cust)
customers["weight"] = customers["size"] / customers["size"].sum()
# some customers start later (new accounts) or stop buying (churn)
customers["first_month"] = np.where(rng.random(450) < 0.15, rng.integers(1, 20, 450), 0)
customers["last_month"] = np.where(rng.random(450) < 0.06, rng.integers(10, 23, 450), 99)

# ---------------------------------------------------------------- sales lines
days = pd.date_range(START, END, freq="D")
def season(d):
    s = 1.0
    if (d.year == 2025 and d.month == 3) or (d.year == 2026 and d.month in (2,)) or (d.year == 2026 and d.month == 3 and d.day < 20): s *= 1.28   # Ramadan
    if d.month in (7, 8): s *= 0.84                                                   # summer
    if d.month == 12: s *= 1.08
    if d.dayofweek == 4: s *= 0.55                                                     # Friday
    return s
trend = lambda d: 1 + 0.085 * ((d - START).days / 365)
cust_w = customers["weight"].to_numpy()
mi = lambda d: (d.year - START.year) * 12 + d.month - START.month
lines = []; inv = 50000
prod_idx = np.arange(P); prod_p = products["popularity"].to_numpy()
price = products["unit_price"].to_numpy(); cost = products["unit_cost"].to_numpy()
cat_arr = products["category"].to_numpy()
cat_names = list(CATS)
cat_code = np.array([cat_names.index(c) for c in cat_arr])
# supplier cost drift: a small random walk per category and month, plus two deliberate events
drift = np.cumsum(rng.normal(0, 0.012, (24, len(cat_names))), axis=0)
drift[21:24, cat_names.index("Beverages")] += 0.07          # Jul to Sep 2026: beverage supplier price rise
drift[17:19, cat_names.index("Dry Grocery")] -= 0.03        # Mar to Apr 2026: better rice and flour buying
cost_mult = 1 + drift
promo_p = np.full(24, 0.30); promo_p[[5, 17, 2, 14]] = 0.48 # heavier discounting in Ramadan months and December
for d in days:
    m = mi(d)
    active = ((customers["first_month"] <= m) & (customers["last_month"] >= m)).to_numpy()
    w = cust_w * active; w = w / w.sum()
    n_inv = rng.poisson(38 * season(d) * trend(d))
    cids = rng.choice(len(customers), n_inv, p=w)
    for c in cids:
        inv += 1
        nl = 1 + rng.poisson(3.1)
        skus = rng.choice(prod_idx, nl, replace=False, p=prod_p)
        crow = customers.iat[c, 0]; br = customers.iat[c, 3]
        disc = 0.0 if rng.random() > promo_p[m] else float(rng.choice([0.02, 0.05, 0.08]))
        for s in skus:
            q = int(rng.integers(1, 6) * rng.choice([1, 2, 6, 12], p=[.35, .3, .25, .1]))
            if cat_arr[s] == "Dry Grocery" and d.month == 3: q = int(q * 1.3) + 1
            lines.append((f"INV{inv}", d, crow, br, products.iat[s, 0], q, price[s], disc, round(cost[s] * cost_mult[m, cat_code[s]], 2)))
sl = pd.DataFrame(lines, columns=["invoice_no", "invoice_date", "customer_id", "branch", "sku", "qty", "unit_price", "discount_pct", "unit_cost"])
sl["net_amount"] = (sl["qty"] * sl["unit_price"] * (1 - sl["discount_pct"])).round(2)
sl["cost_amount"] = (sl["qty"] * sl["unit_cost"]).round(2)
sl = sl.drop(columns="unit_cost")
# credit notes (returns): about 1.2% of lines, negative qty, booked a few days later
ret = sl.sample(frac=0.012, random_state=SEED).copy()
ret["invoice_no"] = ["CN" + x[3:] for x in ret["invoice_no"]]
ret["invoice_date"] = (ret["invoice_date"] + pd.to_timedelta(rng.integers(2, 15, len(ret)), unit="D")).clip(upper=END)
ret["qty"] = -np.maximum(1, (ret["qty"] * rng.uniform(.2, 1, len(ret))).astype(int))
ret["net_amount"] = (ret["qty"] * ret["unit_price"] * (1 - ret["discount_pct"])).round(2)
ret["cost_amount"] = (ret["qty"] * ret["unit_price"] * 0).round(2) + ret["qty"] * products.set_index("sku").loc[ret["sku"], "unit_cost"].to_numpy()
sl = pd.concat([sl, ret]).sort_values(["invoice_date", "invoice_no"]).reset_index(drop=True)
sl["cost_amount"] = sl["cost_amount"].round(2)

# ---------------------------------------------------------------- stock simulation (FIFO lots, reorder rule)
dq = sl[sl.qty > 0].groupby(["sku", "branch", "invoice_date"])["qty"].sum()
lead = products.set_index("sku")["lead_time_days"]
ucost = products.set_index("sku")["unit_cost"]
avg_daily = sl[sl.qty > 0].groupby(["sku", "branch"])["qty"].sum() / len(days)
receipts = []; lots_out = []; rec_n = 70000; reorder_rows = []
day_index = {d: i for i, d in enumerate(days)}
_pairs = list(avg_daily.index)
MISSED = set(_pairs[i] for i in rng.choice(len(_pairs), 30, replace=False))   # items the buyer overlooked recently
open_po = []
for (s, b), ad in avg_daily.items():
    lt = int(lead[s]); sku_slow = bool(slow[products.index[products.sku == s][0]])
    rl = int(np.ceil(ad * (lt + 14))) + 3                    # reorder level: lead time + 2 weeks safety
    oq = max(int(np.ceil(ad * 30)), 6)                       # order quantity: about 30 days
    reorder_rows.append((s, b, rl, oq))
    series = np.zeros(len(days), dtype=int)
    try:
        ser = dq.loc[(s, b)]
        for d, q in ser.items(): series[day_index[d]] = q
    except KeyError: pass
    init = int(ad * 40) + (int(rng.integers(40, 160)) if sku_slow else 0)
    lots = [[START - pd.Timedelta(days=int(rng.integers(20, 200 if sku_slow else 60))), init]]
    on_order = []                                            # (arrival_index, qty)
    for i, d in enumerate(days):
        while on_order and on_order[0][0] == i:
            q = on_order.pop(0)[1]; rec_n += 1
            receipts.append((f"GRN{rec_n}", d, b, s, q, float(ucost[s])))
            lots.append([d, q])
        need = series[i]
        while need > 0 and lots:
            take = min(need, lots[0][1]); lots[0][1] -= take; need -= take
            if lots[0][1] == 0: lots.pop(0)
        oh = sum(l[1] for l in lots); oo = sum(q for _, q in on_order)
        # the slow movers are rarely reordered; a few items are deliberately short at snapshot
        missed = (s, b) in MISSED and i > len(days) - 40
        if d.dayofweek == 0 and oh + oo < rl and not (sku_slow and oh > 0) and not missed:
            jitter = int(rng.integers(0, 4))
            on_order.append((i + lt + jitter, oq if rng.random() > .1 else int(oq * 1.8)))
            on_order.sort()
    for d0, q in lots:
        if q > 0: lots_out.append((b, s, d0, q, float(ucost[s])))
    for ai, q in on_order:
        rec_n += 1; open_po.append((f"PO{rec_n}", b, s, q, days[0] + pd.Timedelta(days=ai)))
purchases = pd.DataFrame(receipts, columns=["receipt_id", "receipt_date", "branch", "sku", "qty", "unit_cost"])
purchases["amount"] = (purchases["qty"] * purchases["unit_cost"]).round(2)
stock_lots = pd.DataFrame(lots_out, columns=["branch", "sku", "receipt_date", "qty_on_hand", "unit_cost"])
open_po = pd.DataFrame(open_po, columns=["po_id", "branch", "sku", "qty_on_order", "expected_date"])
reorder = pd.DataFrame(reorder_rows, columns=["sku", "branch", "reorder_level", "reorder_qty"])

# ---------------------------------------------------------------- invoices (AR) and payments
ih = sl.groupby("invoice_no").agg(invoice_date=("invoice_date", "first"), customer_id=("customer_id", "first"),
                                  branch=("branch", "first"), net_amount=("net_amount", "sum")).reset_index()
ih["vat_amount"] = (ih["net_amount"] * 0.05).round(2)
ih["amount_incl_vat"] = (ih["net_amount"] + ih["vat_amount"]).round(2)
ih = ih.merge(customers[["customer_id", "credit_terms_days", "pay_delay_mean"]], on="customer_id")
ih["due_date"] = ih["invoice_date"] + pd.to_timedelta(np.where(ih.invoice_no.str.startswith("CN"), 0, ih["credit_terms_days"]), unit="D")
delay = rng.normal(ih["pay_delay_mean"], 6 + ih["pay_delay_mean"].abs() * 0.4)
# collections slowed in summer 2026 for some accounts (visible in the DSO trend)
late26 = (ih["invoice_date"] >= "2026-05-01") & (ih["pay_delay_mean"] >= 12)
delay = delay + np.where(late26, rng.uniform(5, 20, len(ih)), 0)
pay = ih["due_date"] + pd.to_timedelta(np.round(delay).astype(int), unit="D")
pay = pay.where(pay > ih["invoice_date"], ih["invoice_date"] + pd.Timedelta(days=1))
never = rng.random(len(ih)) < np.where(ih["pay_delay_mean"] >= 45, 0.08, 0.004)     # disputed or doubtful
ih["paid_date"] = pay.where((pay <= END) & ~never)
ih.loc[ih.invoice_no.str.startswith("CN"), "paid_date"] = ih["invoice_date"]       # credit notes offset immediately
ih["paid_amount"] = np.where(ih["paid_date"].notna(), ih["amount_incl_vat"], 0.0)
invoices = ih[["invoice_no", "invoice_date", "customer_id", "branch", "net_amount", "vat_amount", "amount_incl_vat", "due_date", "paid_date", "paid_amount"]]
# credit limit sized from each customer's typical monthly purchases
mon = invoices.groupby("customer_id")["amount_incl_vat"].sum() / 24
customers["credit_limit"] = (mon.reindex(customers.customer_id).fillna(5000).to_numpy() * customers["credit_terms_days"] / 30 * 1.7 / 1000).round().clip(lower=5) * 1000

# ---------------------------------------------------------------- bank transactions
bank = []
paid = invoices[invoices.paid_date.notna() & ~invoices.invoice_no.str.startswith("CN")]
for r in paid.itertuples():
    bank.append((r.paid_date, "Customer receipt", r.customer_id, r.invoice_no, round(r.paid_amount, 2)))
pw = purchases.copy(); pw["pay_date"] = (pw["receipt_date"] + pd.Timedelta(days=60))
pw = pw[pw.pay_date <= END].groupby(pd.Grouper(key="pay_date", freq="W-THU"))["amount"].sum()
for d, a in pw.items():
    if a > 0: bank.append((d, "Supplier payment", "", "", -round(a * 1.05, 2)))
for m in pd.date_range(START, END, freq="MS"):
    k = mi(m)
    bank.append((m + pd.Timedelta(days=27), "Payroll", "", "", -round(158_000 * (1 + 0.004 * k) + float(rng.normal(0, 9000)), 2)))
    bank.append((m + pd.Timedelta(days=4), "Rent and utilities", "", "", -round(46_000 + float(rng.normal(0, 2500)), 2)))
    bank.append((m + pd.Timedelta(days=10), "Fleet and fuel", "", "", -round(39_000 + float(rng.normal(0, 4000)), 2)))
    if m.month in (1, 7):
        bank.append((m + pd.Timedelta(days=14), "Shareholder distribution", "", "", -300_000.00))
    if m == pd.Timestamp("2026-03-01"):
        bank.append((m + pd.Timedelta(days=17), "Vehicle purchase", "", "", -420_000.00))
    if m.month in (1, 4, 7, 10):
        q_sales = invoices[(invoices.invoice_date < m) & (invoices.invoice_date >= m - pd.DateOffset(months=3))]["vat_amount"].sum()
        bank.append((m + pd.Timedelta(days=27), "VAT payment", "", "", -round(q_sales * 0.25, 2)))
bank = pd.DataFrame(bank, columns=["txn_date", "category", "customer_id", "reference", "amount"])
bank = bank[bank.txn_date <= END].sort_values("txn_date").reset_index(drop=True)
bank.insert(0, "txn_id", [f"BT{100001 + i}" for i in range(len(bank))])
OPENING_CASH = 650_000.00

# ---------------------------------------------------------------- orders (for the chatbot), last 75 days plus open orders
rec = invoices[(invoices.invoice_date > END - pd.Timedelta(days=75)) & invoices.invoice_no.str.startswith("INV")].copy()
cinfo = customers.set_index("customer_id")
orders = []
for r in rec.itertuples():
    od = r.invoice_date - pd.Timedelta(days=int(rng.choice([0, 1, 1, 2])))
    prom = od + pd.Timedelta(days=int(rng.choice([1, 2, 2, 3])))
    late = rng.random() < (0.11 if cinfo.at[r.customer_id, "emirate"] in ("Fujairah", "Ras Al Khaimah") else 0.06)
    deliv = prom + pd.Timedelta(days=int(rng.integers(1, 4))) if late else prom - pd.Timedelta(days=int(rng.choice([0, 0, 1])))
    status = "Delivered" if deliv <= END else "Out for delivery"
    if rng.random() < 0.015: status, deliv = "Cancelled", None
    orders.append([r.invoice_no.replace("INV", "TW-"), od, prom, deliv, status, r.customer_id, r.branch, round(r.amount_incl_vat, 2), r.invoice_no])
# open orders not yet invoiced
over = invoices[invoices.paid_date.isna() & (invoices.due_date < END)].groupby("customer_id")["amount_incl_vat"].sum()
nxt = int(invoices.invoice_no.str[3:].astype(int).max()) + 1
for i in range(160):
    c = customers.sample(1, weights="weight", random_state=SEED + i).iloc[0]
    od = END - pd.Timedelta(days=int(rng.integers(0, 3)))
    st = str(rng.choice(["Received", "Picking", "Packed"], p=[.35, .35, .3]))
    if over.get(c.customer_id, 0) > c.credit_limit * 0.5: st = "On hold, credit check"
    orders.append([f"TW-{nxt + i}", od, od + pd.Timedelta(days=2), None, st, c.customer_id, c.branch, round(float(rng.uniform(300, 9000)), 2), ""])
orders = pd.DataFrame(orders, columns=["order_id", "order_date", "promised_date", "delivered_date", "status", "customer_id", "branch", "order_value", "invoice_no"])
orders["items"] = rng.integers(1, 12, len(orders))

# ---------------------------------------------------------------- write
def w(df, name):
    df.to_csv(os.path.join(OUT, name), index=False, date_format="%Y-%m-%d"); return len(df)
counts = {
    "products.csv": w(products.drop(columns=["popularity"]), "products.csv"),
    "customers.csv": w(customers.drop(columns=["size", "weight", "pay_delay_mean", "first_month", "last_month"]), "customers.csv"),
    "sales_lines.csv": w(sl, "sales_lines.csv"),
    "invoices.csv": w(invoices, "invoices.csv"),
    "purchase_receipts.csv": w(purchases, "purchase_receipts.csv"),
    "stock_lots_snapshot.csv": w(stock_lots, "stock_lots_snapshot.csv"),
    "reorder_settings.csv": w(reorder, "reorder_settings.csv"),
    "open_purchase_orders.csv": w(open_po, "open_purchase_orders.csv"),
    "bank_transactions.csv": w(bank, "bank_transactions.csv"),
    "orders.csv": w(orders, "orders.csv"),
}
meta = {"company": "Tidewell Distribution LLC", "seed": SEED, "period_start": str(START.date()), "snapshot_date": str(END.date()),
        "opening_cash_aed": OPENING_CASH, "row_counts": counts, "total_rows": sum(counts.values())}
json.dump(meta, open(os.path.join(OUT, "meta.json"), "w"), indent=2)
print(json.dumps(meta, indent=2))
